name: acds-moonshot-tycho
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.8
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::cpuonly
  - seaborn
  - numpy<=1.23.5
  - qt
  - pyqt
  - pip
  - pip:
    - -r requirements.txt
